const LEVELS = [
  ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                o                               ",
    "                                                                                ",
    "                                    o o                           x!!!!!!!!!!x  ",
    "                                                                  x!xxxxxxxxxx  ",
    "                                                   xx      xx    xx!xx       x  ",
    "                                             xx                  x!!!x       x  ",
    "                                   xxxxx  o o                    xx!xx       x  ",
    "                                                                  xvx        x  ",
    "  xx                                                                         x  ",
    "  x                                                                      o   x  ",
    "  x                     o                xxxxx                               x  ",
    "  x                                                                          x  ",
    "  x          xxxx       o                                                    x  ",
    "  x  @       x  x                                                xxxxx       x  ",
    "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
    "                              x   x                  x     x                    ",
    "                              x!!!x                  x!!!!!x                    ",
    "                              x!!!x                  x!!!!!x                    ",
    "                              xxxxx                  xxxxxxx                    ",
    "                                                                                ",
    "                                                                                "],
  ["                                                                                                             x!x  ",
    "                                      x!!x                        xxxxxxx                                    x!x  ",
    "                                      x!!x                     xxxx     xxxx                                 x!x  ",
    "                                      x!!xxxxxxxxxx           xx           xx                o   o   o   o   x!x  ",
    "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
    "                                       xxxxxxxxxx!!x         x                                               x!x  ",
    "                                                xx!x         x     o   o                                    xx!x  ",
    "                                                 x!x         x                          xxxxxxxxxxxxxxxxxxxxx!!x  ",
    "                                                 xvx         x     x   x                x!!!!!!!!!!!!!!!!!!!!!xx  ",
    "                                                             xx  |   |   |  xx         xx!xxxxxxxxxxxxxxxxxxxxx   ",
    "                                                              xx!!!!!!!!!!!xx            v                        ",
    "                                                               xxxx!!!!!xxxx                                      ",
    "                                               x     x            xxxxxxx        xxx         xxx                  ",
    "                                               x     x                           x x         x x                  ",
    "                                               x     x                             x         x                    ",
    "                                               x     x                        o    xx        x                    ",
    "                                               xx    x       o                     x         x                    ",
    "                                               x     x                   x         x         x                    ",
    "               xxxxxxx        xxx   xxx        x     x                   x         x         x                    ",
    "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
    "             xx       xx        x o x          x    xx               x   x   x               x                    ",
    "     @       x         x        x   x          x     x              ox   xxxxx               x                    ",
    "    xxx      x         x        x   x          x     x             xxx                       x                    ",
    "    x x      x         x       xx o xx         x     x               x     o     xxxxxx      x                    ",
    "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!!!!x           x x     o   x                    ",
    "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xxxxxxxxx     =     x xx       xx                    ",
    "!!!!x x!!!!!!x         x!!!!!x                       xx!!!!!!xx      xxxxxxxxxxxxx  xx     xx                     ",
    "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx                       xxxxxxx                      ",
    "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx                                                     ",
    "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx                                                      ",
    "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
    "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                        o                                                                     ",
    "                                                                                                              ",
    "                                        x                                                                     ",
    "                                        x                                                                     ",
    "                                        x                                                                     ",
    "                                        x                                                                     ",
    "                                       xxx                                 xxx                                ",
    "                                       x x                 !!!    =   !!!                                     ",
    "                                       x x                 !x! o oo o !x!                                     ",
    "                                     xxx xxx                x          x                                      ",
    "                                      x   x                 x          x       xxx                            ",
    "                                      x   x                 x          x      x!!!x                           ",
    "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
    "                                     xx   xx          x      x                                                ",
    "                                      x   x      x    xxxxxxxx              x  x                              ",
    "                                      x   xxxxxxxx    x                    x!!!!x                             ",
    "                                      x   x           x                     xxxx                              ",
    "                                     xx   xxx         x                                                       ",
    "                                      x   x= = = =    x            xxx                   o                    ",
    "                                      x   x           x           x!!!x                                       ",
    "                                      x   x    = = = =x     o      xxx       xxx                              ",
    "                              o   o  xx   xxx         x                     x!!!x                             ",
    "                                      x   x  o        x     x                xxv         xx                   ",
    "                                      x   x        o  x              x                  x!!x                  ",
    "                             xxx xx   xxxxx           x!!!!!!!!!!!!!!x                   vx              xxx  ",
    "                             x xxx   xxxxxx           x!!!!!!!!!!!!!!x                                   x x  ",
    "                             x            x    xxxxxxxxxxxxxxxxxxxxxxx                                     x  ",
    "                             xx           xx                                         xxx                   x  ",
    "  xxx                         x           x       |                                 x!!!x                  x  ",
    "  x x                         x     x     x                    o |                   xxx                   x  ",
    "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
    "  x                           x    xxx    x                              x   x                             x  ",
    "  x                           xx          x o                            x x x                             x  ",
    "  x                                       x        xxxx|     xxxx      xxx xxx                             x  ",
    "  x                xxx             o o    x                              x         xxx                     x  ",
    "  x               xxxxx                   x     o         o         o   xxx       x!!!x          x         x  ",
    "  x               oxxxo       xx   xxx    x                 |           x x        xxx          xxx        x  ",
    "  x                xxx        xxxxxxxxxxxxx  x    x    x    x    x     xx xx                    xxx        x  ",
    "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                                              ",
    "                                                                                                              "],
  ["                                                                                                  x           ",
    "                                                                                                  xxxxx       ",
    "                                                                                                      x       ",
    "                                                                                                  xxxxx       ",
    "                                                                      o       o       o           x           ",
    "                          o                                                                       xxxxx       ",
    "                                                                                                      x       ",
    "                   xxx                                            xxxxxx xxxxxx  xxxxx   x   x o x xxxx       ",
    "       !  o  !                                                    x    x x       x      x x  xx xx x          ",
    "       x     x                                                    x    x x       x     x   x x x x x          ",
    "       x= o  x            x                                o  xxx xxxxxx xxxxxx  x  xx xxxxx x x x xxxx       ",
    "       x     x                                                    x  x        x  x   x x   x x   x x          ",
    "       !  o  !            o                                       x   x       x  x   x x   x x   x x          ",
    "       |                                                          x    x xxxxxx  xxxxx x   x x   x xxxx       ",
    "          o              xxx                              xx                                                  ",
    "                                                                                   o                          ",
    "                          o                                                                                   ",
    "                                                      xx                                                      ",
    "  x                xxx    |    xxx                                                                            ",
    "  x                                                                                                           ",
    "  x                       o                                                     x      x                      ",
    "  x                                                       xx     xx                                           ",
    "  x         xxxx         xxx         xxx                                 x                  x                 ",
    "  x     x   x o                                                                                               ",
    "  x!!!!!xx  x                                                    ||                                           ",
    "  xxxxxxx   x                                                                                                 ",
    "  x         xx  xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
    "  x          x  x       x   x       x   x                 ||                  x     x                         ",
    "  x  @       xxxx   o   xxxxx   o   xxxxx                                                                     ",
    "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
    "        x                                     x   x                     xxx                                   ",
    "        x=                   =               =x   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                                                              "]
];

export {LEVELS} ;